#!/usr/bin/env groovy
pipeline {
    agent {
        dockerfile true
    }
    stages {
        stage('build') {
            steps {
                sh 'composer install'
            }
        }
        stage('database') {
            steps {
                sh 'docker-compose up -d'
            }
        }
        stage('migrations') {
            steps {
                sh 'vendor/bin/phinx migrate -e development'
            }
        }
        stage('tests') {
            steps {
                sh 'vendor/bin/phpunit src/tests'
            }
        }
        stage('start') {
            steps {
                sh 'php -S localhost:8080'
            }
        }
    }
}
