#!/usr/bin/env groovy
pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'apt-get update -y'
                sh 'apt-get install composer'
                sh 'composer install'
            }
        }
        stage('database') {
            steps {
                sh 'docker-compose up -d'
            }
        }
        stage('migrations') {
            steps {
                sh 'vendor/bin/phpunit src/tests'
            }
        }
        stage('tests') {
            steps {
                sh 'vendor/bin/phpunit src/tests'
            }
        }
        stage('start') {
            steps {
                sh 'php -S localhost:8080'
            }
        }
    }
}
